# Generated by Django 4.0.4 on 2023-03-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_chat_name_friendschat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_slug',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
