# Generated by Django 4.0.4 on 2023-04-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_contact_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendschat',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
