# Generated by Django 4.0.4 on 2023-04-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_friendschat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='online',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
