# Generated by Django 4.0.4 on 2023-04-10 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_contact_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onlineforfriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.DateTimeField(auto_now=True)),
                ('friendchat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.friendschat')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.contact')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineforChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.contact')),
            ],
        ),
    ]
