# Generated by Django 4.0.4 on 2023-05-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chat_image_contact_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='admins', to='chat.contact'),
        ),
    ]
