# Generated by Django 4.0.4 on 2023-05-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chat_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='restrict',
            field=models.ManyToManyField(blank=True, related_name='restrictions', to='chat.contact'),
        ),
    ]
