# Generated by Django 4.0.4 on 2023-05-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_chat_restrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendschat',
            name='restrict',
            field=models.ManyToManyField(blank=True, related_name='restrictFriend', to='chat.contact'),
        ),
    ]
